apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ajuo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-ajuo@sha256:a9f14212368d72ffd04aca18953df5ce013eb6a29355866021d4d118de717c0c
        name: my-nodejs
        resources: {}
status: {}
